name: Deploy to Ubuntu Server

on:
  push:
    branches: ["develop"]  
  pull_request:
    branches: ["develop"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      # - name: Build and test
      #   run: |
      #     npm install
      #     npm test

      - name: Handle Private SSH keys
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "start .. SSH_PRIVATE_KEY"
          eval "$(ssh-agent -s)"
          ssh-add <(echo "$SSH_PRIVATE_KEY" | base64 --decode)
          # ssh-add <(echo ${SSH_PRIVATE_KEY})
          # ssh-add - <<< "$SSH_PRIVATE_KEY"
          echo "End .. SSH_PRIVATE_KEY"
      #   shell: bash

      # - name: GIT clone
      #   run: |
      #     echo "$SSH_PRIVATE_KEY"
      #     # cd ~/projects/crud
      #     cd ~/
      #     echo "Home directory"
      #     git clone git@github.com:MichaelKasingye/Pius-CRUD-psql-docker-typeorm.git
      #     echo "git clone"
      #   shell: bash


      - name: Deploy to server
        uses: easingthemes/ssh-deploy@main
        with:
          run: echo "$SSH_PRIVATE_KEY"
          # username: ${{ secrets.SERVER_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.SERVER_USER }}
          # key: ${{ secrets.SSH_KEY }}
          # ssh-key: ${{ secrets.SSH_KEY }}
          # key: ${{ secrets.SSH_KEY }}
          script: |
            echo "$Accessing the remote system"
            cd ~/projects/crud
            echo "$Here In the System"
            # git clone git@github.com:MichaelKasingye/Pius-CRUD-psql-docker-typeorm.git
            # git pull 
            # npm install
            # npm start
            # pm2 restart crud
