name: Deploy to Ubuntu Server

on:
  push:
    branches: ["develop"]  
  pull_request:
    branches: ["develop"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      # - name: Build and test
      #   run: |
      #     npm install
      #     npm test

      - name: Handle Private SSH keys
        run: |
          eval "$(ssh-agent -s)"
          ssh-add - <<< "$SSH_PRIVATE_KEY"
          echo "$SSH_PRIVATE_KEY"
          ssh-add <(echo "$SSH_PRIVATE_KEY")
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          # ssh-key: ${{ secrets.SSH_KEY }}
          # key: ${{ secrets.SSH_KEY }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd ~/projects/crud
            git pull 
            npm install
            npm start
            pm2 restart crud
