name: Deploy to Ubuntu Server

on:
  push:
    branches: ["develop"]  
  pull_request:
    branches: ["develop"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      # - name: Build and test
      #   run: |
      #     npm install
      #     npm test

      # - name: Handle Private SSH keys
      #   run: echo "$SSH_PRIVATE_KEY"
      #   run: |
      #     eval "$(ssh-agent -s)"
      #     ssh-add - <<< "$SSH_PRIVATE_KEY"
      #     echo "$SSH_PRIVATE_KEY"
      #   shell: bash
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: GIT clone
        run: |
          echo "$SSH_PRIVATE_KEY"
          # cd ~/projects/crud
          cd ~/
          echo "Home directory"
          # git clone git@github.com:MichaelKasingye/Pius-CRUD-psql-docker-typeorm.git
        shell: bash


      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.8
        with:
          # run: echo "$SSH_PRIVATE_KEY"
          # username: ${{ secrets.SERVER_USER }}
          # host: ${{ secrets.SERVER_HOST }}
          # password: ${{ secrets.SERVER_PASSWORD }}
          # ssh-key: ${{ secrets.SSH_KEY }}
          # key: ${{ secrets.SSH_KEY }}
          # port: ${{ secrets.SERVER_PORT }}
          # key: ${{ secrets.SSH_KEY }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/projects/crud
            git clone git@github.com:MichaelKasingye/Pius-CRUD-psql-docker-typeorm.git
            git pull 
            npm install
            npm start
            pm2 restart crud
